### ISSUE TITLE
missing: images/outfit/paint.png

### ISSUE THREAD

**Issue by EndrosG** [Wrzlprnft/world-forge#46]
The swizzle data file defines outfits which refer to a "paint" sprite. I dont find it in the images folder. And it is not included in the vanilla version of the game.

**Comment by Amazinite** [comment]
The idea for the paint outfits originally came from an old plugin called Project Runabout, which in it has the paint image. I guess Wrzl never realized that he hadn't actually copied over the paint sprite and only the data for the outfits.
In 152510e I've added the sprite, but editted it so that the color of the paint matches the color of the swizzle that it changes your ship to.

**Comment by EndrosG** [comment]
tyvm :+1:
